import "@/app/globals.css";
import { Poppins } from "next/font/google";
import 'animate.css'
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => (
  <html lang="en" className={`scroll-smooth ${poppins.className}`}>
    <body className="bg-gray-100 min-h-screen">
      {children}
      <Footer />
    </body>
  </html>
);

export default RootLayout;
